name: Windows ARM64 Debugging with tmate

on: 
  workflow_dispatch: # Lazım olduqda paneldən əl ilə başladılması üçün

jobs:
  debug-windows-arm:
    # Rəsmi Windows 11 ARM64 runner-i çağırmaq üçün təyin edilən etiket
    runs-on: windows-11-arm
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # tmate-in işləməsi üçün lazım olan MSYS2 mühitini quraşdırır
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: tmate

      # İndi tmate problemsiz işə düşəcək
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          detached: false
          limit-access-to-actor: true
