name: Debug macOS Workflow
on: workflow_dispatch

jobs:
  debug-mac:
    runs-on: macos-26  # Supports the macOS environments
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Place this step exactly where you want the build to pause for debugging
      - name: Setup Tmate SSH Session
        uses: mxschmitt/action-tmate@v3
