jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      # Install and run sshx
      - name: Start sshx
        shell: pwsh
        run: |
          Invoke-Expression (Invoke-RestMethod https://sshx.io)
          sshx
